### ISSUE TITLE
It doesn't works on python 3.7.

### ISSUE THREAD

**Issue by Victor-Lerman** [tallforasmurf/byteplay#15]
```
Traceback (most recent call last):
  File "/Users/admin/Documents/byteplaying.py", line 1, in <module>
    from byteplay3 import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/byteplay3.py", line 400, in <module>
    hascode = set( [ Opcode(MAKE_FUNCTION), Opcode(MAKE_CLOSURE) ] )
NameError: name 'MAKE_CLOSURE' is not defined
```

**Comment by tallforasmurf** [comment]
Please refer to the top heading in the README,
https://github.com/tallforasmurf/byteplay#stop-changes

The point being, it didn't work in Python 3.6, either, for a more serious reason, namely, they changed everything about the bytecode format!

Should I pull it out of pypi? Probably! I am sorry you lost any time trying to use it.

**Comment by serprex** [comment]
I updated my byteplay fork with wbyteplay when I submitted 3.6's wordcode patch: https://github.com/serprex/byteplay

But I stopped maintaining my fork after bytecode became a thing shortly after, so I doubt it works on latest Python versions
